language: python

python: 3.6

branches: master

before_install:
    - openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in deploy-key.enc -out deploy-key -d

install:
    - pip install mkdocs

script:
    - mkdocs build

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: docs
    on:
        branch: master
    fqdn: docs.snoring.ninja
