language: python

python: 3.6

branches: master

install:
    - pip install mkdocs

script:
    - mkdocs build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs
    on:
        branch: master
    fqdn: docs.snoring.ninja
