language: python

python: 3.6

branches: master

install:
    - pip install mkdocs
    - pip install mkdocs-material

script:
    - mkdocs build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs
    on:
        branch: master
